version: "3.1"

services:
  destore-database:
    image: "destore/database:latest"
    container_name: "destore-database"
    ports:
      - "5432:5432"
    restart: "unless-stopped"
    volumes:
      # Persistent data
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    labels:
      container-check: enabled
networks:
  default:
    external:
      name: "destore-network"
